### ISSUE TITLE
A place for improvement - ReadME

### ISSUE THREAD

**Issue by maciekkoz98** [PatrykZaniewski/medManager#2]
As I mentioned in the topic, there is a big place for improvement. I recommend you to add readme document in order to specify what this application really does.
Best wishes,
Maciej

**Comment by PatrykZaniewski** [comment]
JUST LEAVE ME ALONE I KNOW WHAT TO DO

**Comment by maciekkoz98** [comment]
BUT I DON'T KNOW WHAT THIS REPOSITORY IS ABOUT!
